# Generated by Django 3.2.2 on 2021-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.CharField(default=11111111, max_length=100),
            preserve_default=False,
        ),
    ]
