# Generated by Django 3.2.2 on 2021-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=99999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
