# Generated by Django 3.2.2 on 2021-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
