# Generated by Django 3.2.2 on 2021-05-16 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='realeseddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
