# Generated by Django 3.2.2 on 2021-05-16 12:03

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
